apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      tier: frontend
  template:
    metadata:
      labels:
        app: frontend
        tier: frontend
    spec:
      containers:
      - name: frontend
        image: audesu/frontend:online
        ports:
        - containerPort: 80
        env:
        - name: REACT_APP_BACKEND_URL
          value: http://backend-service:5000
        lifecycle:
          preStop:
            exec:
              command: ["/usr/sbin/nginx", "-s", "quit"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:  
      app: backend
      tier: backend
  template:
    metadata:
      labels:
        app: backend 
        tier: backend 
    spec:
      containers:
      - name: backend
        image: audesu/backend:latest 
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URI
          value: mongodb://db-service:27017/wishlist

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: mongo
        image: mongo
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
      volumes:
      - name: mongo-data
        emptyDir: {}
