
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
      - name: cloudflared
        image: {{ .Values.cloudflared.image.repository }}:{{ .Values.cloudflared.image.tag }}
        args:
        - tunnel
        - --no-autoupdate
        - run
        
        env:
        - name: TUNNEL_TOKEN
          valueFrom:
            secretKeyRef:
              name: cloudflare-tunnel-token
              key: tunnel-token
        volumeMounts:
        - name: cloudflared-config
          mountPath: /etc/cloudflared/config.yml
          subPath: config.yml
      volumes:
      - name: cloudflared-config
        configMap:
          name: cloudflared-config



