frontend:
  replicaCount: 1
  env:
    REACT_APP_BACKEND_URL: "http://test-backend-service:5000"  

backend:
  replicaCount: 1
  env:
    MONGO_URI: "mongodb://test-db-service:27017/wishlist" 

db:
  replicaCount: 1
  env:
    MONGO_URI: "mongodb://test-db-service:27017/wishlist" 

frontendService:
  port: 80
  targetPort: 80

dbService:
  type: ClusterIP
  port: 27017
  targetPort: 27017
