frontend:
  replicaCount: 1
  image:
    repository: audesu/frontend
    tag: dev
  env:
    REACT_APP_BACKEND_URL: "http://34.76.13.160:5000"

backend:
  replicaCount: 1
  env:
    MONGO_URI: "mongodb://wishlist-development-db-service:27017/wishlist"


db:
  replicaCount: 1


frontendService:
  port: 80
  targetPort: 80

dbService:
  type: ClusterIP
  port: 27017
  targetPort: 27017
